---
abstract: 'Module for any OneTool onetool_*.pl program'
author:
  - 'Sebastien Thebert <contact@onetool.pm>'
build_requires:
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.013, CPAN::Meta::Converter version 2.132830'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: OneTool-App-Core
requires:
  FindBin: '0'
  HTTP::Daemon: '0'
  HTTP::Headers: '0'
  HTTP::Response: '0'
  HTTP::Status: '0'
  IO::Socket::SSL: '0'
  Log::Log4perl: '0'
  Log::Log4perl::Level: '0'
  Moose: '0'
  OneTool::Core: '0.1'
  URI: '0'
  URI::QueryParam: '0'
version: '0.1'
